package com.hl.contract.table.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.hl.contract.table.model.CallRecord;
import com.hl.contract.table.model.CargoFeeInfo;
import com.hl.contract.table.model.CargoMainInfo;
import com.hl.contract.table.model.Contract;
import com.hl.contract.table.model.DictInfo;
import com.hl.contract.table.model.DriverInfo;
import com.hl.contract.table.model.EvalLossInfo;
import com.hl.contract.table.model.HistoricalPaymentInfo;
import com.hl.contract.table.model.HistoricalReportInfo;
import com.hl.contract.table.model.InjuryFeeInfo;
import com.hl.contract.table.model.InjuryHospitalInfo;
import com.hl.contract.table.model.InjuryMainInfo;
import com.hl.contract.table.model.Insurance;
import com.hl.contract.table.model.InsuranceCar;
import com.hl.contract.table.model.InsuranceItem;
import com.hl.contract.table.model.MemoInfo;
import com.hl.contract.table.model.PolicyInfo;
import com.hl.contract.table.model.ReportCar;
import com.hl.contract.table.model.ReportCarLossPart;
import com.hl.contract.table.model.ReportInfo;
import com.hl.contract.table.model.SearchRecords;
import com.hl.contract.table.model.SubrogationData;
import com.hl.contract.table.model.SurveyAimCar;
import com.hl.contract.table.model.SurveyExtendInfo;
import com.hl.contract.table.model.SurveyInjury;
import com.hl.contract.table.model.SurveyMainInfo;
import com.hl.contract.table.model.SurveyPayment;
import com.hl.contract.table.model.SurveyProperty;
import com.hl.contract.table.model.TaskInfo;
import com.hl.contract.table.model.UserInfo;

import com.hl.contract.table.dao.CallRecordDao;
import com.hl.contract.table.dao.CargoFeeInfoDao;
import com.hl.contract.table.dao.CargoMainInfoDao;
import com.hl.contract.table.dao.ContractDao;
import com.hl.contract.table.dao.DictInfoDao;
import com.hl.contract.table.dao.DriverInfoDao;
import com.hl.contract.table.dao.EvalLossInfoDao;
import com.hl.contract.table.dao.HistoricalPaymentInfoDao;
import com.hl.contract.table.dao.HistoricalReportInfoDao;
import com.hl.contract.table.dao.InjuryFeeInfoDao;
import com.hl.contract.table.dao.InjuryHospitalInfoDao;
import com.hl.contract.table.dao.InjuryMainInfoDao;
import com.hl.contract.table.dao.InsuranceDao;
import com.hl.contract.table.dao.InsuranceCarDao;
import com.hl.contract.table.dao.InsuranceItemDao;
import com.hl.contract.table.dao.MemoInfoDao;
import com.hl.contract.table.dao.PolicyInfoDao;
import com.hl.contract.table.dao.ReportCarDao;
import com.hl.contract.table.dao.ReportCarLossPartDao;
import com.hl.contract.table.dao.ReportInfoDao;
import com.hl.contract.table.dao.SearchRecordsDao;
import com.hl.contract.table.dao.SubrogationDataDao;
import com.hl.contract.table.dao.SurveyAimCarDao;
import com.hl.contract.table.dao.SurveyExtendInfoDao;
import com.hl.contract.table.dao.SurveyInjuryDao;
import com.hl.contract.table.dao.SurveyMainInfoDao;
import com.hl.contract.table.dao.SurveyPaymentDao;
import com.hl.contract.table.dao.SurveyPropertyDao;
import com.hl.contract.table.dao.TaskInfoDao;
import com.hl.contract.table.dao.UserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig callRecordDaoConfig;
    private final DaoConfig cargoFeeInfoDaoConfig;
    private final DaoConfig cargoMainInfoDaoConfig;
    private final DaoConfig contractDaoConfig;
    private final DaoConfig dictInfoDaoConfig;
    private final DaoConfig driverInfoDaoConfig;
    private final DaoConfig evalLossInfoDaoConfig;
    private final DaoConfig historicalPaymentInfoDaoConfig;
    private final DaoConfig historicalReportInfoDaoConfig;
    private final DaoConfig injuryFeeInfoDaoConfig;
    private final DaoConfig injuryHospitalInfoDaoConfig;
    private final DaoConfig injuryMainInfoDaoConfig;
    private final DaoConfig insuranceDaoConfig;
    private final DaoConfig insuranceCarDaoConfig;
    private final DaoConfig insuranceItemDaoConfig;
    private final DaoConfig memoInfoDaoConfig;
    private final DaoConfig policyInfoDaoConfig;
    private final DaoConfig reportCarDaoConfig;
    private final DaoConfig reportCarLossPartDaoConfig;
    private final DaoConfig reportInfoDaoConfig;
    private final DaoConfig searchRecordsDaoConfig;
    private final DaoConfig subrogationDataDaoConfig;
    private final DaoConfig surveyAimCarDaoConfig;
    private final DaoConfig surveyExtendInfoDaoConfig;
    private final DaoConfig surveyInjuryDaoConfig;
    private final DaoConfig surveyMainInfoDaoConfig;
    private final DaoConfig surveyPaymentDaoConfig;
    private final DaoConfig surveyPropertyDaoConfig;
    private final DaoConfig taskInfoDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final CallRecordDao callRecordDao;
    private final CargoFeeInfoDao cargoFeeInfoDao;
    private final CargoMainInfoDao cargoMainInfoDao;
    private final ContractDao contractDao;
    private final DictInfoDao dictInfoDao;
    private final DriverInfoDao driverInfoDao;
    private final EvalLossInfoDao evalLossInfoDao;
    private final HistoricalPaymentInfoDao historicalPaymentInfoDao;
    private final HistoricalReportInfoDao historicalReportInfoDao;
    private final InjuryFeeInfoDao injuryFeeInfoDao;
    private final InjuryHospitalInfoDao injuryHospitalInfoDao;
    private final InjuryMainInfoDao injuryMainInfoDao;
    private final InsuranceDao insuranceDao;
    private final InsuranceCarDao insuranceCarDao;
    private final InsuranceItemDao insuranceItemDao;
    private final MemoInfoDao memoInfoDao;
    private final PolicyInfoDao policyInfoDao;
    private final ReportCarDao reportCarDao;
    private final ReportCarLossPartDao reportCarLossPartDao;
    private final ReportInfoDao reportInfoDao;
    private final SearchRecordsDao searchRecordsDao;
    private final SubrogationDataDao subrogationDataDao;
    private final SurveyAimCarDao surveyAimCarDao;
    private final SurveyExtendInfoDao surveyExtendInfoDao;
    private final SurveyInjuryDao surveyInjuryDao;
    private final SurveyMainInfoDao surveyMainInfoDao;
    private final SurveyPaymentDao surveyPaymentDao;
    private final SurveyPropertyDao surveyPropertyDao;
    private final TaskInfoDao taskInfoDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        callRecordDaoConfig = daoConfigMap.get(CallRecordDao.class).clone();
        callRecordDaoConfig.initIdentityScope(type);

        cargoFeeInfoDaoConfig = daoConfigMap.get(CargoFeeInfoDao.class).clone();
        cargoFeeInfoDaoConfig.initIdentityScope(type);

        cargoMainInfoDaoConfig = daoConfigMap.get(CargoMainInfoDao.class).clone();
        cargoMainInfoDaoConfig.initIdentityScope(type);

        contractDaoConfig = daoConfigMap.get(ContractDao.class).clone();
        contractDaoConfig.initIdentityScope(type);

        dictInfoDaoConfig = daoConfigMap.get(DictInfoDao.class).clone();
        dictInfoDaoConfig.initIdentityScope(type);

        driverInfoDaoConfig = daoConfigMap.get(DriverInfoDao.class).clone();
        driverInfoDaoConfig.initIdentityScope(type);

        evalLossInfoDaoConfig = daoConfigMap.get(EvalLossInfoDao.class).clone();
        evalLossInfoDaoConfig.initIdentityScope(type);

        historicalPaymentInfoDaoConfig = daoConfigMap.get(HistoricalPaymentInfoDao.class).clone();
        historicalPaymentInfoDaoConfig.initIdentityScope(type);

        historicalReportInfoDaoConfig = daoConfigMap.get(HistoricalReportInfoDao.class).clone();
        historicalReportInfoDaoConfig.initIdentityScope(type);

        injuryFeeInfoDaoConfig = daoConfigMap.get(InjuryFeeInfoDao.class).clone();
        injuryFeeInfoDaoConfig.initIdentityScope(type);

        injuryHospitalInfoDaoConfig = daoConfigMap.get(InjuryHospitalInfoDao.class).clone();
        injuryHospitalInfoDaoConfig.initIdentityScope(type);

        injuryMainInfoDaoConfig = daoConfigMap.get(InjuryMainInfoDao.class).clone();
        injuryMainInfoDaoConfig.initIdentityScope(type);

        insuranceDaoConfig = daoConfigMap.get(InsuranceDao.class).clone();
        insuranceDaoConfig.initIdentityScope(type);

        insuranceCarDaoConfig = daoConfigMap.get(InsuranceCarDao.class).clone();
        insuranceCarDaoConfig.initIdentityScope(type);

        insuranceItemDaoConfig = daoConfigMap.get(InsuranceItemDao.class).clone();
        insuranceItemDaoConfig.initIdentityScope(type);

        memoInfoDaoConfig = daoConfigMap.get(MemoInfoDao.class).clone();
        memoInfoDaoConfig.initIdentityScope(type);

        policyInfoDaoConfig = daoConfigMap.get(PolicyInfoDao.class).clone();
        policyInfoDaoConfig.initIdentityScope(type);

        reportCarDaoConfig = daoConfigMap.get(ReportCarDao.class).clone();
        reportCarDaoConfig.initIdentityScope(type);

        reportCarLossPartDaoConfig = daoConfigMap.get(ReportCarLossPartDao.class).clone();
        reportCarLossPartDaoConfig.initIdentityScope(type);

        reportInfoDaoConfig = daoConfigMap.get(ReportInfoDao.class).clone();
        reportInfoDaoConfig.initIdentityScope(type);

        searchRecordsDaoConfig = daoConfigMap.get(SearchRecordsDao.class).clone();
        searchRecordsDaoConfig.initIdentityScope(type);

        subrogationDataDaoConfig = daoConfigMap.get(SubrogationDataDao.class).clone();
        subrogationDataDaoConfig.initIdentityScope(type);

        surveyAimCarDaoConfig = daoConfigMap.get(SurveyAimCarDao.class).clone();
        surveyAimCarDaoConfig.initIdentityScope(type);

        surveyExtendInfoDaoConfig = daoConfigMap.get(SurveyExtendInfoDao.class).clone();
        surveyExtendInfoDaoConfig.initIdentityScope(type);

        surveyInjuryDaoConfig = daoConfigMap.get(SurveyInjuryDao.class).clone();
        surveyInjuryDaoConfig.initIdentityScope(type);

        surveyMainInfoDaoConfig = daoConfigMap.get(SurveyMainInfoDao.class).clone();
        surveyMainInfoDaoConfig.initIdentityScope(type);

        surveyPaymentDaoConfig = daoConfigMap.get(SurveyPaymentDao.class).clone();
        surveyPaymentDaoConfig.initIdentityScope(type);

        surveyPropertyDaoConfig = daoConfigMap.get(SurveyPropertyDao.class).clone();
        surveyPropertyDaoConfig.initIdentityScope(type);

        taskInfoDaoConfig = daoConfigMap.get(TaskInfoDao.class).clone();
        taskInfoDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        callRecordDao = new CallRecordDao(callRecordDaoConfig, this);
        cargoFeeInfoDao = new CargoFeeInfoDao(cargoFeeInfoDaoConfig, this);
        cargoMainInfoDao = new CargoMainInfoDao(cargoMainInfoDaoConfig, this);
        contractDao = new ContractDao(contractDaoConfig, this);
        dictInfoDao = new DictInfoDao(dictInfoDaoConfig, this);
        driverInfoDao = new DriverInfoDao(driverInfoDaoConfig, this);
        evalLossInfoDao = new EvalLossInfoDao(evalLossInfoDaoConfig, this);
        historicalPaymentInfoDao = new HistoricalPaymentInfoDao(historicalPaymentInfoDaoConfig, this);
        historicalReportInfoDao = new HistoricalReportInfoDao(historicalReportInfoDaoConfig, this);
        injuryFeeInfoDao = new InjuryFeeInfoDao(injuryFeeInfoDaoConfig, this);
        injuryHospitalInfoDao = new InjuryHospitalInfoDao(injuryHospitalInfoDaoConfig, this);
        injuryMainInfoDao = new InjuryMainInfoDao(injuryMainInfoDaoConfig, this);
        insuranceDao = new InsuranceDao(insuranceDaoConfig, this);
        insuranceCarDao = new InsuranceCarDao(insuranceCarDaoConfig, this);
        insuranceItemDao = new InsuranceItemDao(insuranceItemDaoConfig, this);
        memoInfoDao = new MemoInfoDao(memoInfoDaoConfig, this);
        policyInfoDao = new PolicyInfoDao(policyInfoDaoConfig, this);
        reportCarDao = new ReportCarDao(reportCarDaoConfig, this);
        reportCarLossPartDao = new ReportCarLossPartDao(reportCarLossPartDaoConfig, this);
        reportInfoDao = new ReportInfoDao(reportInfoDaoConfig, this);
        searchRecordsDao = new SearchRecordsDao(searchRecordsDaoConfig, this);
        subrogationDataDao = new SubrogationDataDao(subrogationDataDaoConfig, this);
        surveyAimCarDao = new SurveyAimCarDao(surveyAimCarDaoConfig, this);
        surveyExtendInfoDao = new SurveyExtendInfoDao(surveyExtendInfoDaoConfig, this);
        surveyInjuryDao = new SurveyInjuryDao(surveyInjuryDaoConfig, this);
        surveyMainInfoDao = new SurveyMainInfoDao(surveyMainInfoDaoConfig, this);
        surveyPaymentDao = new SurveyPaymentDao(surveyPaymentDaoConfig, this);
        surveyPropertyDao = new SurveyPropertyDao(surveyPropertyDaoConfig, this);
        taskInfoDao = new TaskInfoDao(taskInfoDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(CallRecord.class, callRecordDao);
        registerDao(CargoFeeInfo.class, cargoFeeInfoDao);
        registerDao(CargoMainInfo.class, cargoMainInfoDao);
        registerDao(Contract.class, contractDao);
        registerDao(DictInfo.class, dictInfoDao);
        registerDao(DriverInfo.class, driverInfoDao);
        registerDao(EvalLossInfo.class, evalLossInfoDao);
        registerDao(HistoricalPaymentInfo.class, historicalPaymentInfoDao);
        registerDao(HistoricalReportInfo.class, historicalReportInfoDao);
        registerDao(InjuryFeeInfo.class, injuryFeeInfoDao);
        registerDao(InjuryHospitalInfo.class, injuryHospitalInfoDao);
        registerDao(InjuryMainInfo.class, injuryMainInfoDao);
        registerDao(Insurance.class, insuranceDao);
        registerDao(InsuranceCar.class, insuranceCarDao);
        registerDao(InsuranceItem.class, insuranceItemDao);
        registerDao(MemoInfo.class, memoInfoDao);
        registerDao(PolicyInfo.class, policyInfoDao);
        registerDao(ReportCar.class, reportCarDao);
        registerDao(ReportCarLossPart.class, reportCarLossPartDao);
        registerDao(ReportInfo.class, reportInfoDao);
        registerDao(SearchRecords.class, searchRecordsDao);
        registerDao(SubrogationData.class, subrogationDataDao);
        registerDao(SurveyAimCar.class, surveyAimCarDao);
        registerDao(SurveyExtendInfo.class, surveyExtendInfoDao);
        registerDao(SurveyInjury.class, surveyInjuryDao);
        registerDao(SurveyMainInfo.class, surveyMainInfoDao);
        registerDao(SurveyPayment.class, surveyPaymentDao);
        registerDao(SurveyProperty.class, surveyPropertyDao);
        registerDao(TaskInfo.class, taskInfoDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        callRecordDaoConfig.clearIdentityScope();
        cargoFeeInfoDaoConfig.clearIdentityScope();
        cargoMainInfoDaoConfig.clearIdentityScope();
        contractDaoConfig.clearIdentityScope();
        dictInfoDaoConfig.clearIdentityScope();
        driverInfoDaoConfig.clearIdentityScope();
        evalLossInfoDaoConfig.clearIdentityScope();
        historicalPaymentInfoDaoConfig.clearIdentityScope();
        historicalReportInfoDaoConfig.clearIdentityScope();
        injuryFeeInfoDaoConfig.clearIdentityScope();
        injuryHospitalInfoDaoConfig.clearIdentityScope();
        injuryMainInfoDaoConfig.clearIdentityScope();
        insuranceDaoConfig.clearIdentityScope();
        insuranceCarDaoConfig.clearIdentityScope();
        insuranceItemDaoConfig.clearIdentityScope();
        memoInfoDaoConfig.clearIdentityScope();
        policyInfoDaoConfig.clearIdentityScope();
        reportCarDaoConfig.clearIdentityScope();
        reportCarLossPartDaoConfig.clearIdentityScope();
        reportInfoDaoConfig.clearIdentityScope();
        searchRecordsDaoConfig.clearIdentityScope();
        subrogationDataDaoConfig.clearIdentityScope();
        surveyAimCarDaoConfig.clearIdentityScope();
        surveyExtendInfoDaoConfig.clearIdentityScope();
        surveyInjuryDaoConfig.clearIdentityScope();
        surveyMainInfoDaoConfig.clearIdentityScope();
        surveyPaymentDaoConfig.clearIdentityScope();
        surveyPropertyDaoConfig.clearIdentityScope();
        taskInfoDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
    }

    public CallRecordDao getCallRecordDao() {
        return callRecordDao;
    }

    public CargoFeeInfoDao getCargoFeeInfoDao() {
        return cargoFeeInfoDao;
    }

    public CargoMainInfoDao getCargoMainInfoDao() {
        return cargoMainInfoDao;
    }

    public ContractDao getContractDao() {
        return contractDao;
    }

    public DictInfoDao getDictInfoDao() {
        return dictInfoDao;
    }

    public DriverInfoDao getDriverInfoDao() {
        return driverInfoDao;
    }

    public EvalLossInfoDao getEvalLossInfoDao() {
        return evalLossInfoDao;
    }

    public HistoricalPaymentInfoDao getHistoricalPaymentInfoDao() {
        return historicalPaymentInfoDao;
    }

    public HistoricalReportInfoDao getHistoricalReportInfoDao() {
        return historicalReportInfoDao;
    }

    public InjuryFeeInfoDao getInjuryFeeInfoDao() {
        return injuryFeeInfoDao;
    }

    public InjuryHospitalInfoDao getInjuryHospitalInfoDao() {
        return injuryHospitalInfoDao;
    }

    public InjuryMainInfoDao getInjuryMainInfoDao() {
        return injuryMainInfoDao;
    }

    public InsuranceDao getInsuranceDao() {
        return insuranceDao;
    }

    public InsuranceCarDao getInsuranceCarDao() {
        return insuranceCarDao;
    }

    public InsuranceItemDao getInsuranceItemDao() {
        return insuranceItemDao;
    }

    public MemoInfoDao getMemoInfoDao() {
        return memoInfoDao;
    }

    public PolicyInfoDao getPolicyInfoDao() {
        return policyInfoDao;
    }

    public ReportCarDao getReportCarDao() {
        return reportCarDao;
    }

    public ReportCarLossPartDao getReportCarLossPartDao() {
        return reportCarLossPartDao;
    }

    public ReportInfoDao getReportInfoDao() {
        return reportInfoDao;
    }

    public SearchRecordsDao getSearchRecordsDao() {
        return searchRecordsDao;
    }

    public SubrogationDataDao getSubrogationDataDao() {
        return subrogationDataDao;
    }

    public SurveyAimCarDao getSurveyAimCarDao() {
        return surveyAimCarDao;
    }

    public SurveyExtendInfoDao getSurveyExtendInfoDao() {
        return surveyExtendInfoDao;
    }

    public SurveyInjuryDao getSurveyInjuryDao() {
        return surveyInjuryDao;
    }

    public SurveyMainInfoDao getSurveyMainInfoDao() {
        return surveyMainInfoDao;
    }

    public SurveyPaymentDao getSurveyPaymentDao() {
        return surveyPaymentDao;
    }

    public SurveyPropertyDao getSurveyPropertyDao() {
        return surveyPropertyDao;
    }

    public TaskInfoDao getTaskInfoDao() {
        return taskInfoDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
