package com.hl.contract.table.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.hl.contract.table.model.SubrogationData;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SUBROGATION_DATA".
*/
public class SubrogationDataDao extends AbstractDao<SubrogationData, String> {

    public static final String TABLENAME = "SUBROGATION_DATA";

    /**
     * Properties of entity SubrogationData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property ReportCode = new Property(1, String.class, "reportCode", false, "REPORT_CODE");
        public final static Property FlowId = new Property(2, String.class, "flowId", false, "FLOW_ID");
        public final static Property SubrogationSerialNo = new Property(3, int.class, "subrogationSerialNo", false, "SUBROGATION_SERIAL_NO");
        public final static Property SubrogationLinkerName = new Property(4, String.class, "subrogationLinkerName", false, "SUBROGATION_LINKER_NAME");
        public final static Property SubrogationCarType = new Property(5, String.class, "subrogationCarType", false, "SUBROGATION_CAR_TYPE");
        public final static Property SubrogationCarTypeCode = new Property(6, String.class, "subrogationCarTypeCode", false, "SUBROGATION_CAR_TYPE_CODE");
        public final static Property SubrogationEngineNo = new Property(7, String.class, "subrogationEngineNo", false, "SUBROGATION_ENGINE_NO");
        public final static Property SubrogationLicensePlateNo = new Property(8, String.class, "subrogationLicensePlateNo", false, "SUBROGATION_LICENSE_PLATE_NO");
        public final static Property SubrogationLicensePlateType = new Property(9, String.class, "subrogationLicensePlateType", false, "SUBROGATION_LICENSE_PLATE_TYPE");
        public final static Property SubrogationLicensePlateTypeCode = new Property(10, String.class, "subrogationLicensePlateTypeCode", false, "SUBROGATION_LICENSE_PLATE_TYPE_CODE");
        public final static Property SubrogationVIN = new Property(11, String.class, "subrogationVIN", false, "SUBROGATION_VIN");
        public final static Property SubrogationCaInsurerCodeSY = new Property(12, String.class, "subrogationCaInsurerCodeSY", false, "SUBROGATION_CA_INSURER_CODE_SY");
        public final static Property SubrogationCaInsurerCodeSYCompaName = new Property(13, String.class, "subrogationCaInsurerCodeSYCompaName", false, "SUBROGATION_CA_INSURER_CODE_SYCOMPA_NAME");
        public final static Property SubrogationCaInsurerCodeSYDQ = new Property(14, String.class, "subrogationCaInsurerCodeSYDQ", false, "SUBROGATION_CA_INSURER_CODE_SYDQ");
        public final static Property SubrogationCaInsurerCodeSYDQArea = new Property(15, String.class, "subrogationCaInsurerCodeSYDQArea", false, "SUBROGATION_CA_INSURER_CODE_SYDQAREA");
        public final static Property SubrogationCaInsurerCodeJQ = new Property(16, String.class, "subrogationCaInsurerCodeJQ", false, "SUBROGATION_CA_INSURER_CODE_JQ");
        public final static Property SubrogationCaInsurerCodeJQCompaName = new Property(17, String.class, "subrogationCaInsurerCodeJQCompaName", false, "SUBROGATION_CA_INSURER_CODE_JQCOMPA_NAME");
        public final static Property SubrogationCaInsurerCodeJQDQ = new Property(18, String.class, "subrogationCaInsurerCodeJQDQ", false, "SUBROGATION_CA_INSURER_CODE_JQDQ");
        public final static Property SubrogationCaInsurerCodeJQDQArea = new Property(19, String.class, "subrogationCaInsurerCodeJQDQArea", false, "SUBROGATION_CA_INSURER_CODE_JQDQAREA");
        public final static Property SubrogationCaInsurerUnit = new Property(20, String.class, "subrogationCaInsurerUnit", false, "SUBROGATION_CA_INSURER_UNIT");
        public final static Property SubrogationCaInsurerPhone = new Property(21, String.class, "subrogationCaInsurerPhone", false, "SUBROGATION_CA_INSURER_PHONE");
        public final static Property SubrogationCaInsurerDriver = new Property(22, String.class, "subrogationCaInsurerDriver", false, "SUBROGATION_CA_INSURER_DRIVER");
        public final static Property SubrogationDriverPhone = new Property(23, String.class, "subrogationDriverPhone", false, "SUBROGATION_DRIVER_PHONE");
        public final static Property SubrogationUnitPhone = new Property(24, String.class, "subrogationUnitPhone", false, "SUBROGATION_UNIT_PHONE");
        public final static Property SubrogationAmount = new Property(25, double.class, "subrogationAmount", false, "SUBROGATION_AMOUNT");
        public final static Property SubrogationFlag = new Property(26, String.class, "subrogationFlag", false, "SUBROGATION_FLAG");
        public final static Property SubrogationCaInsurerLinkerName = new Property(27, String.class, "subrogationCaInsurerLinkerName", false, "SUBROGATION_CA_INSURER_LINKER_NAME");
        public final static Property SubrogationAdress = new Property(28, String.class, "subrogationAdress", false, "SUBROGATION_ADRESS");
        public final static Property SubrogationPostcode = new Property(29, String.class, "subrogationPostcode", false, "SUBROGATION_POSTCODE");
        public final static Property SubrogationCertificateId = new Property(30, String.class, "subrogationCertificateId", false, "SUBROGATION_CERTIFICATE_ID");
        public final static Property SubrogationCaInsurerStartDate = new Property(31, String.class, "subrogationCaInsurerStartDate", false, "SUBROGATION_CA_INSURER_START_DATE");
        public final static Property SubrogationCaInsurerEndDate = new Property(32, String.class, "subrogationCaInsurerEndDate", false, "SUBROGATION_CA_INSURER_END_DATE");
        public final static Property SubrogationBusCaInsurerStartDate = new Property(33, String.class, "subrogationBusCaInsurerStartDate", false, "SUBROGATION_BUS_CA_INSURER_START_DATE");
        public final static Property SubrogationBusCaInsurerEndDate = new Property(34, String.class, "subrogationBusCaInsurerEndDate", false, "SUBROGATION_BUS_CA_INSURER_END_DATE");
        public final static Property SubrogationLegalRepresentative = new Property(35, String.class, "subrogationLegalRepresentative", false, "SUBROGATION_LEGAL_REPRESENTATIVE");
        public final static Property SubrogationInsurance = new Property(36, String.class, "subrogationInsurance", false, "SUBROGATION_INSURANCE");
    }


    public SubrogationDataDao(DaoConfig config) {
        super(config);
    }
    
    public SubrogationDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SUBROGATION_DATA\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"REPORT_CODE\" TEXT," + // 1: reportCode
                "\"FLOW_ID\" TEXT," + // 2: flowId
                "\"SUBROGATION_SERIAL_NO\" INTEGER NOT NULL ," + // 3: subrogationSerialNo
                "\"SUBROGATION_LINKER_NAME\" TEXT," + // 4: subrogationLinkerName
                "\"SUBROGATION_CAR_TYPE\" TEXT," + // 5: subrogationCarType
                "\"SUBROGATION_CAR_TYPE_CODE\" TEXT," + // 6: subrogationCarTypeCode
                "\"SUBROGATION_ENGINE_NO\" TEXT," + // 7: subrogationEngineNo
                "\"SUBROGATION_LICENSE_PLATE_NO\" TEXT," + // 8: subrogationLicensePlateNo
                "\"SUBROGATION_LICENSE_PLATE_TYPE\" TEXT," + // 9: subrogationLicensePlateType
                "\"SUBROGATION_LICENSE_PLATE_TYPE_CODE\" TEXT," + // 10: subrogationLicensePlateTypeCode
                "\"SUBROGATION_VIN\" TEXT," + // 11: subrogationVIN
                "\"SUBROGATION_CA_INSURER_CODE_SY\" TEXT," + // 12: subrogationCaInsurerCodeSY
                "\"SUBROGATION_CA_INSURER_CODE_SYCOMPA_NAME\" TEXT," + // 13: subrogationCaInsurerCodeSYCompaName
                "\"SUBROGATION_CA_INSURER_CODE_SYDQ\" TEXT," + // 14: subrogationCaInsurerCodeSYDQ
                "\"SUBROGATION_CA_INSURER_CODE_SYDQAREA\" TEXT," + // 15: subrogationCaInsurerCodeSYDQArea
                "\"SUBROGATION_CA_INSURER_CODE_JQ\" TEXT," + // 16: subrogationCaInsurerCodeJQ
                "\"SUBROGATION_CA_INSURER_CODE_JQCOMPA_NAME\" TEXT," + // 17: subrogationCaInsurerCodeJQCompaName
                "\"SUBROGATION_CA_INSURER_CODE_JQDQ\" TEXT," + // 18: subrogationCaInsurerCodeJQDQ
                "\"SUBROGATION_CA_INSURER_CODE_JQDQAREA\" TEXT," + // 19: subrogationCaInsurerCodeJQDQArea
                "\"SUBROGATION_CA_INSURER_UNIT\" TEXT," + // 20: subrogationCaInsurerUnit
                "\"SUBROGATION_CA_INSURER_PHONE\" TEXT," + // 21: subrogationCaInsurerPhone
                "\"SUBROGATION_CA_INSURER_DRIVER\" TEXT," + // 22: subrogationCaInsurerDriver
                "\"SUBROGATION_DRIVER_PHONE\" TEXT," + // 23: subrogationDriverPhone
                "\"SUBROGATION_UNIT_PHONE\" TEXT," + // 24: subrogationUnitPhone
                "\"SUBROGATION_AMOUNT\" REAL NOT NULL ," + // 25: subrogationAmount
                "\"SUBROGATION_FLAG\" TEXT," + // 26: subrogationFlag
                "\"SUBROGATION_CA_INSURER_LINKER_NAME\" TEXT," + // 27: subrogationCaInsurerLinkerName
                "\"SUBROGATION_ADRESS\" TEXT," + // 28: subrogationAdress
                "\"SUBROGATION_POSTCODE\" TEXT," + // 29: subrogationPostcode
                "\"SUBROGATION_CERTIFICATE_ID\" TEXT," + // 30: subrogationCertificateId
                "\"SUBROGATION_CA_INSURER_START_DATE\" TEXT," + // 31: subrogationCaInsurerStartDate
                "\"SUBROGATION_CA_INSURER_END_DATE\" TEXT," + // 32: subrogationCaInsurerEndDate
                "\"SUBROGATION_BUS_CA_INSURER_START_DATE\" TEXT," + // 33: subrogationBusCaInsurerStartDate
                "\"SUBROGATION_BUS_CA_INSURER_END_DATE\" TEXT," + // 34: subrogationBusCaInsurerEndDate
                "\"SUBROGATION_LEGAL_REPRESENTATIVE\" TEXT," + // 35: subrogationLegalRepresentative
                "\"SUBROGATION_INSURANCE\" TEXT);"); // 36: subrogationInsurance
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SUBROGATION_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SubrogationData entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String reportCode = entity.getReportCode();
        if (reportCode != null) {
            stmt.bindString(2, reportCode);
        }
 
        String flowId = entity.getFlowId();
        if (flowId != null) {
            stmt.bindString(3, flowId);
        }
        stmt.bindLong(4, entity.getSubrogationSerialNo());
 
        String subrogationLinkerName = entity.getSubrogationLinkerName();
        if (subrogationLinkerName != null) {
            stmt.bindString(5, subrogationLinkerName);
        }
 
        String subrogationCarType = entity.getSubrogationCarType();
        if (subrogationCarType != null) {
            stmt.bindString(6, subrogationCarType);
        }
 
        String subrogationCarTypeCode = entity.getSubrogationCarTypeCode();
        if (subrogationCarTypeCode != null) {
            stmt.bindString(7, subrogationCarTypeCode);
        }
 
        String subrogationEngineNo = entity.getSubrogationEngineNo();
        if (subrogationEngineNo != null) {
            stmt.bindString(8, subrogationEngineNo);
        }
 
        String subrogationLicensePlateNo = entity.getSubrogationLicensePlateNo();
        if (subrogationLicensePlateNo != null) {
            stmt.bindString(9, subrogationLicensePlateNo);
        }
 
        String subrogationLicensePlateType = entity.getSubrogationLicensePlateType();
        if (subrogationLicensePlateType != null) {
            stmt.bindString(10, subrogationLicensePlateType);
        }
 
        String subrogationLicensePlateTypeCode = entity.getSubrogationLicensePlateTypeCode();
        if (subrogationLicensePlateTypeCode != null) {
            stmt.bindString(11, subrogationLicensePlateTypeCode);
        }
 
        String subrogationVIN = entity.getSubrogationVIN();
        if (subrogationVIN != null) {
            stmt.bindString(12, subrogationVIN);
        }
 
        String subrogationCaInsurerCodeSY = entity.getSubrogationCaInsurerCodeSY();
        if (subrogationCaInsurerCodeSY != null) {
            stmt.bindString(13, subrogationCaInsurerCodeSY);
        }
 
        String subrogationCaInsurerCodeSYCompaName = entity.getSubrogationCaInsurerCodeSYCompaName();
        if (subrogationCaInsurerCodeSYCompaName != null) {
            stmt.bindString(14, subrogationCaInsurerCodeSYCompaName);
        }
 
        String subrogationCaInsurerCodeSYDQ = entity.getSubrogationCaInsurerCodeSYDQ();
        if (subrogationCaInsurerCodeSYDQ != null) {
            stmt.bindString(15, subrogationCaInsurerCodeSYDQ);
        }
 
        String subrogationCaInsurerCodeSYDQArea = entity.getSubrogationCaInsurerCodeSYDQArea();
        if (subrogationCaInsurerCodeSYDQArea != null) {
            stmt.bindString(16, subrogationCaInsurerCodeSYDQArea);
        }
 
        String subrogationCaInsurerCodeJQ = entity.getSubrogationCaInsurerCodeJQ();
        if (subrogationCaInsurerCodeJQ != null) {
            stmt.bindString(17, subrogationCaInsurerCodeJQ);
        }
 
        String subrogationCaInsurerCodeJQCompaName = entity.getSubrogationCaInsurerCodeJQCompaName();
        if (subrogationCaInsurerCodeJQCompaName != null) {
            stmt.bindString(18, subrogationCaInsurerCodeJQCompaName);
        }
 
        String subrogationCaInsurerCodeJQDQ = entity.getSubrogationCaInsurerCodeJQDQ();
        if (subrogationCaInsurerCodeJQDQ != null) {
            stmt.bindString(19, subrogationCaInsurerCodeJQDQ);
        }
 
        String subrogationCaInsurerCodeJQDQArea = entity.getSubrogationCaInsurerCodeJQDQArea();
        if (subrogationCaInsurerCodeJQDQArea != null) {
            stmt.bindString(20, subrogationCaInsurerCodeJQDQArea);
        }
 
        String subrogationCaInsurerUnit = entity.getSubrogationCaInsurerUnit();
        if (subrogationCaInsurerUnit != null) {
            stmt.bindString(21, subrogationCaInsurerUnit);
        }
 
        String subrogationCaInsurerPhone = entity.getSubrogationCaInsurerPhone();
        if (subrogationCaInsurerPhone != null) {
            stmt.bindString(22, subrogationCaInsurerPhone);
        }
 
        String subrogationCaInsurerDriver = entity.getSubrogationCaInsurerDriver();
        if (subrogationCaInsurerDriver != null) {
            stmt.bindString(23, subrogationCaInsurerDriver);
        }
 
        String subrogationDriverPhone = entity.getSubrogationDriverPhone();
        if (subrogationDriverPhone != null) {
            stmt.bindString(24, subrogationDriverPhone);
        }
 
        String subrogationUnitPhone = entity.getSubrogationUnitPhone();
        if (subrogationUnitPhone != null) {
            stmt.bindString(25, subrogationUnitPhone);
        }
        stmt.bindDouble(26, entity.getSubrogationAmount());
 
        String subrogationFlag = entity.getSubrogationFlag();
        if (subrogationFlag != null) {
            stmt.bindString(27, subrogationFlag);
        }
 
        String subrogationCaInsurerLinkerName = entity.getSubrogationCaInsurerLinkerName();
        if (subrogationCaInsurerLinkerName != null) {
            stmt.bindString(28, subrogationCaInsurerLinkerName);
        }
 
        String subrogationAdress = entity.getSubrogationAdress();
        if (subrogationAdress != null) {
            stmt.bindString(29, subrogationAdress);
        }
 
        String subrogationPostcode = entity.getSubrogationPostcode();
        if (subrogationPostcode != null) {
            stmt.bindString(30, subrogationPostcode);
        }
 
        String subrogationCertificateId = entity.getSubrogationCertificateId();
        if (subrogationCertificateId != null) {
            stmt.bindString(31, subrogationCertificateId);
        }
 
        String subrogationCaInsurerStartDate = entity.getSubrogationCaInsurerStartDate();
        if (subrogationCaInsurerStartDate != null) {
            stmt.bindString(32, subrogationCaInsurerStartDate);
        }
 
        String subrogationCaInsurerEndDate = entity.getSubrogationCaInsurerEndDate();
        if (subrogationCaInsurerEndDate != null) {
            stmt.bindString(33, subrogationCaInsurerEndDate);
        }
 
        String subrogationBusCaInsurerStartDate = entity.getSubrogationBusCaInsurerStartDate();
        if (subrogationBusCaInsurerStartDate != null) {
            stmt.bindString(34, subrogationBusCaInsurerStartDate);
        }
 
        String subrogationBusCaInsurerEndDate = entity.getSubrogationBusCaInsurerEndDate();
        if (subrogationBusCaInsurerEndDate != null) {
            stmt.bindString(35, subrogationBusCaInsurerEndDate);
        }
 
        String subrogationLegalRepresentative = entity.getSubrogationLegalRepresentative();
        if (subrogationLegalRepresentative != null) {
            stmt.bindString(36, subrogationLegalRepresentative);
        }
 
        String subrogationInsurance = entity.getSubrogationInsurance();
        if (subrogationInsurance != null) {
            stmt.bindString(37, subrogationInsurance);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SubrogationData entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String reportCode = entity.getReportCode();
        if (reportCode != null) {
            stmt.bindString(2, reportCode);
        }
 
        String flowId = entity.getFlowId();
        if (flowId != null) {
            stmt.bindString(3, flowId);
        }
        stmt.bindLong(4, entity.getSubrogationSerialNo());
 
        String subrogationLinkerName = entity.getSubrogationLinkerName();
        if (subrogationLinkerName != null) {
            stmt.bindString(5, subrogationLinkerName);
        }
 
        String subrogationCarType = entity.getSubrogationCarType();
        if (subrogationCarType != null) {
            stmt.bindString(6, subrogationCarType);
        }
 
        String subrogationCarTypeCode = entity.getSubrogationCarTypeCode();
        if (subrogationCarTypeCode != null) {
            stmt.bindString(7, subrogationCarTypeCode);
        }
 
        String subrogationEngineNo = entity.getSubrogationEngineNo();
        if (subrogationEngineNo != null) {
            stmt.bindString(8, subrogationEngineNo);
        }
 
        String subrogationLicensePlateNo = entity.getSubrogationLicensePlateNo();
        if (subrogationLicensePlateNo != null) {
            stmt.bindString(9, subrogationLicensePlateNo);
        }
 
        String subrogationLicensePlateType = entity.getSubrogationLicensePlateType();
        if (subrogationLicensePlateType != null) {
            stmt.bindString(10, subrogationLicensePlateType);
        }
 
        String subrogationLicensePlateTypeCode = entity.getSubrogationLicensePlateTypeCode();
        if (subrogationLicensePlateTypeCode != null) {
            stmt.bindString(11, subrogationLicensePlateTypeCode);
        }
 
        String subrogationVIN = entity.getSubrogationVIN();
        if (subrogationVIN != null) {
            stmt.bindString(12, subrogationVIN);
        }
 
        String subrogationCaInsurerCodeSY = entity.getSubrogationCaInsurerCodeSY();
        if (subrogationCaInsurerCodeSY != null) {
            stmt.bindString(13, subrogationCaInsurerCodeSY);
        }
 
        String subrogationCaInsurerCodeSYCompaName = entity.getSubrogationCaInsurerCodeSYCompaName();
        if (subrogationCaInsurerCodeSYCompaName != null) {
            stmt.bindString(14, subrogationCaInsurerCodeSYCompaName);
        }
 
        String subrogationCaInsurerCodeSYDQ = entity.getSubrogationCaInsurerCodeSYDQ();
        if (subrogationCaInsurerCodeSYDQ != null) {
            stmt.bindString(15, subrogationCaInsurerCodeSYDQ);
        }
 
        String subrogationCaInsurerCodeSYDQArea = entity.getSubrogationCaInsurerCodeSYDQArea();
        if (subrogationCaInsurerCodeSYDQArea != null) {
            stmt.bindString(16, subrogationCaInsurerCodeSYDQArea);
        }
 
        String subrogationCaInsurerCodeJQ = entity.getSubrogationCaInsurerCodeJQ();
        if (subrogationCaInsurerCodeJQ != null) {
            stmt.bindString(17, subrogationCaInsurerCodeJQ);
        }
 
        String subrogationCaInsurerCodeJQCompaName = entity.getSubrogationCaInsurerCodeJQCompaName();
        if (subrogationCaInsurerCodeJQCompaName != null) {
            stmt.bindString(18, subrogationCaInsurerCodeJQCompaName);
        }
 
        String subrogationCaInsurerCodeJQDQ = entity.getSubrogationCaInsurerCodeJQDQ();
        if (subrogationCaInsurerCodeJQDQ != null) {
            stmt.bindString(19, subrogationCaInsurerCodeJQDQ);
        }
 
        String subrogationCaInsurerCodeJQDQArea = entity.getSubrogationCaInsurerCodeJQDQArea();
        if (subrogationCaInsurerCodeJQDQArea != null) {
            stmt.bindString(20, subrogationCaInsurerCodeJQDQArea);
        }
 
        String subrogationCaInsurerUnit = entity.getSubrogationCaInsurerUnit();
        if (subrogationCaInsurerUnit != null) {
            stmt.bindString(21, subrogationCaInsurerUnit);
        }
 
        String subrogationCaInsurerPhone = entity.getSubrogationCaInsurerPhone();
        if (subrogationCaInsurerPhone != null) {
            stmt.bindString(22, subrogationCaInsurerPhone);
        }
 
        String subrogationCaInsurerDriver = entity.getSubrogationCaInsurerDriver();
        if (subrogationCaInsurerDriver != null) {
            stmt.bindString(23, subrogationCaInsurerDriver);
        }
 
        String subrogationDriverPhone = entity.getSubrogationDriverPhone();
        if (subrogationDriverPhone != null) {
            stmt.bindString(24, subrogationDriverPhone);
        }
 
        String subrogationUnitPhone = entity.getSubrogationUnitPhone();
        if (subrogationUnitPhone != null) {
            stmt.bindString(25, subrogationUnitPhone);
        }
        stmt.bindDouble(26, entity.getSubrogationAmount());
 
        String subrogationFlag = entity.getSubrogationFlag();
        if (subrogationFlag != null) {
            stmt.bindString(27, subrogationFlag);
        }
 
        String subrogationCaInsurerLinkerName = entity.getSubrogationCaInsurerLinkerName();
        if (subrogationCaInsurerLinkerName != null) {
            stmt.bindString(28, subrogationCaInsurerLinkerName);
        }
 
        String subrogationAdress = entity.getSubrogationAdress();
        if (subrogationAdress != null) {
            stmt.bindString(29, subrogationAdress);
        }
 
        String subrogationPostcode = entity.getSubrogationPostcode();
        if (subrogationPostcode != null) {
            stmt.bindString(30, subrogationPostcode);
        }
 
        String subrogationCertificateId = entity.getSubrogationCertificateId();
        if (subrogationCertificateId != null) {
            stmt.bindString(31, subrogationCertificateId);
        }
 
        String subrogationCaInsurerStartDate = entity.getSubrogationCaInsurerStartDate();
        if (subrogationCaInsurerStartDate != null) {
            stmt.bindString(32, subrogationCaInsurerStartDate);
        }
 
        String subrogationCaInsurerEndDate = entity.getSubrogationCaInsurerEndDate();
        if (subrogationCaInsurerEndDate != null) {
            stmt.bindString(33, subrogationCaInsurerEndDate);
        }
 
        String subrogationBusCaInsurerStartDate = entity.getSubrogationBusCaInsurerStartDate();
        if (subrogationBusCaInsurerStartDate != null) {
            stmt.bindString(34, subrogationBusCaInsurerStartDate);
        }
 
        String subrogationBusCaInsurerEndDate = entity.getSubrogationBusCaInsurerEndDate();
        if (subrogationBusCaInsurerEndDate != null) {
            stmt.bindString(35, subrogationBusCaInsurerEndDate);
        }
 
        String subrogationLegalRepresentative = entity.getSubrogationLegalRepresentative();
        if (subrogationLegalRepresentative != null) {
            stmt.bindString(36, subrogationLegalRepresentative);
        }
 
        String subrogationInsurance = entity.getSubrogationInsurance();
        if (subrogationInsurance != null) {
            stmt.bindString(37, subrogationInsurance);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public SubrogationData readEntity(Cursor cursor, int offset) {
        SubrogationData entity = new SubrogationData( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // reportCode
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // flowId
            cursor.getInt(offset + 3), // subrogationSerialNo
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // subrogationLinkerName
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // subrogationCarType
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // subrogationCarTypeCode
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // subrogationEngineNo
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // subrogationLicensePlateNo
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // subrogationLicensePlateType
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // subrogationLicensePlateTypeCode
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // subrogationVIN
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // subrogationCaInsurerCodeSY
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // subrogationCaInsurerCodeSYCompaName
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // subrogationCaInsurerCodeSYDQ
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // subrogationCaInsurerCodeSYDQArea
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // subrogationCaInsurerCodeJQ
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // subrogationCaInsurerCodeJQCompaName
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // subrogationCaInsurerCodeJQDQ
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // subrogationCaInsurerCodeJQDQArea
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // subrogationCaInsurerUnit
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // subrogationCaInsurerPhone
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // subrogationCaInsurerDriver
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // subrogationDriverPhone
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // subrogationUnitPhone
            cursor.getDouble(offset + 25), // subrogationAmount
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // subrogationFlag
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // subrogationCaInsurerLinkerName
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // subrogationAdress
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // subrogationPostcode
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30), // subrogationCertificateId
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // subrogationCaInsurerStartDate
            cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32), // subrogationCaInsurerEndDate
            cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33), // subrogationBusCaInsurerStartDate
            cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34), // subrogationBusCaInsurerEndDate
            cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35), // subrogationLegalRepresentative
            cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36) // subrogationInsurance
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SubrogationData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setReportCode(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setFlowId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSubrogationSerialNo(cursor.getInt(offset + 3));
        entity.setSubrogationLinkerName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setSubrogationCarType(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setSubrogationCarTypeCode(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setSubrogationEngineNo(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setSubrogationLicensePlateNo(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setSubrogationLicensePlateType(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setSubrogationLicensePlateTypeCode(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setSubrogationVIN(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setSubrogationCaInsurerCodeSY(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setSubrogationCaInsurerCodeSYCompaName(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setSubrogationCaInsurerCodeSYDQ(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setSubrogationCaInsurerCodeSYDQArea(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setSubrogationCaInsurerCodeJQ(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setSubrogationCaInsurerCodeJQCompaName(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setSubrogationCaInsurerCodeJQDQ(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setSubrogationCaInsurerCodeJQDQArea(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setSubrogationCaInsurerUnit(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setSubrogationCaInsurerPhone(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setSubrogationCaInsurerDriver(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setSubrogationDriverPhone(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setSubrogationUnitPhone(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setSubrogationAmount(cursor.getDouble(offset + 25));
        entity.setSubrogationFlag(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setSubrogationCaInsurerLinkerName(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setSubrogationAdress(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setSubrogationPostcode(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setSubrogationCertificateId(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
        entity.setSubrogationCaInsurerStartDate(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setSubrogationCaInsurerEndDate(cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32));
        entity.setSubrogationBusCaInsurerStartDate(cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33));
        entity.setSubrogationBusCaInsurerEndDate(cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34));
        entity.setSubrogationLegalRepresentative(cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35));
        entity.setSubrogationInsurance(cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36));
     }
    
    @Override
    protected final String updateKeyAfterInsert(SubrogationData entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(SubrogationData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SubrogationData entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
